import ast
from collections.abc import Callable as Callable

class ifThis:
    class nameIsC:
        def __new__(cls, allegedly: str) -> Callable[[ast.AST], bool]: ...
    @staticmethod
    def nameIsD(allegedly: str) -> Callable[[ast.AST], bool]: ...
    @staticmethod
    def subscriptNameIsD(allegedly: str) -> Callable[[ast.AST], bool]: ...
    @staticmethod
    def NameReallyIsD(allegedly: str) -> Callable[[ast.AST], bool]: ...
    @staticmethod
    def anyOfD(*predicates: Callable[[ast.AST], bool]) -> Callable[[ast.AST], bool]: ...
