extend = "../../ruff.toml"

[lint]
ignore   = [
	"undocumented-public-module",
	"undocumented-public-function",
	"line-too-long",
	"global-statement",
	"unnecessary-assign",
	"typing-only-first-party-import",
	"missing-whitespace-around-parameter-equals",
]
