extend = "../../ruff.toml"

[lint]
ignore = [
  "global-statement",
  "line-too-long",
  "missing-whitespace-around-parameter-equals",
  "typing-only-first-party-import",
  "undocumented-public-function",
  "undocumented-public-module",
  "unnecessary-assign",
  "unnecessary-cast-to-int",
]
