extend = "../ruff.toml"

[lint]
ignore = [
  "commented-out-code",
  "import-private-name",
  "p-print",
  "print",
  "repeated-append",
  "undocumented-public-function",
  "undocumented-public-module",
]
