import os
from collections.abc import Sequence as Sequence
from numpy import dtype as dtype, integer as integer, ndarray as ndarray
from pathlib import Path

def saveFoldsTotal(pathFilename: str | os.PathLike[str], foldsTotal: int) -> None: ...
def getFilenameFoldsTotal(mapShape: tuple[int, ...]) -> str: ...
def getPathFilenameFoldsTotal(mapShape: tuple[int, ...], pathLikeWriteFoldsTotal: str | os.PathLike[str] | None = None) -> Path: ...
