import enum
from typing import Any, Final

class EnumIndices(enum.IntEnum):
    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: list[Any]) -> int:
        """0-indexed."""
    def __index__(self) -> int:
        """Adapt enum to the ultra-rare event of indexing a NumPy 'ndarray', which is not the
\t\tsame as `array.array`. See NumPy.org; I think it will be very popular someday."""

class indexMy(EnumIndices):
    """Indices for scalar values."""
    dimensionsTotal = ...
    dimensionsUnconstrained = ...
    gap1ndex = ...
    gap1ndexCeiling = ...
    indexDimension = ...
    indexLeaf = ...
    indexMiniGap = ...
    leaf1ndex = ...
    leafConnectee = ...
    taskDivisions = ...
    taskIndex = ...

class indexTrack(EnumIndices):
    """Indices for state tracking array."""
    leafAbove = ...
    leafBelow = ...
    countDimensionsGapped = ...
    gapRangeStart = ...

_datatypeDefault: Final[dict[str, str]]
_datatypeModule: str
_datatypeModuleDEFAULT: Final[str]
_datatype: dict[str, str]

def reportDatatypeLimit(identifier: str, datatype: str, sourGrapes: bool | None = False) -> str: ...
def setDatatypeModule(datatypeModule: str, sourGrapes: bool | None = False) -> str: ...
def setDatatypeElephino(datatype: str, sourGrapes: bool | None = False) -> str: ...
def setDatatypeFoldsTotal(datatype: str, sourGrapes: bool | None = False) -> str: ...
def setDatatypeLeavesTotal(datatype: str, sourGrapes: bool | None = False) -> str: ...
def _get_datatype(identifier: str) -> str: ...
def getDatatypeModule() -> str: ...
def setInStone(identifier: str) -> type[Any]: ...
def hackSSOTdtype(identifier: str) -> type[Any]: ...
def hackSSOTdatatype(identifier: str) -> str: ...
