import pathlib
from mapFolding import getAlgorithmSource as getAlgorithmSource, getPathSyntheticModules as getPathSyntheticModules, setDatatypeElephino as setDatatypeElephino, setDatatypeFoldsTotal as setDatatypeFoldsTotal, setDatatypeLeavesTotal as setDatatypeLeavesTotal, setDatatypeModule as setDatatypeModule

def transformPythonToJAX(codePython: str) -> None: ...
def writeJax(*, codeSource: str | None = None, pathFilenameAlgorithm: pathlib.Path | None = None, pathFilenameDestination: pathlib.Path | None = None) -> None: ...
