import ast
from mapFolding import ParametersNumba as ParametersNumba, Z0Z_getDatatypeModuleScalar as Z0Z_getDatatypeModuleScalar, Z0Z_getDecoratorCallable as Z0Z_getDecoratorCallable, parametersNumbaDEFAULT as parametersNumbaDEFAULT
from mapFolding.someAssemblyRequired import Then as Then, LedgerOfImports as LedgerOfImports, ifThis as ifThis

def thisIsNumbaDotJit(Ima: ast.AST) -> bool: ...
def thisIsJit(Ima: ast.AST) -> bool: ...
def thisIsAnyNumbaJitDecorator(Ima: ast.AST) -> bool: ...
def decorateCallableWithNumba(FunctionDefTarget: ast.FunctionDef, allImports: LedgerOfImports, parametersNumba: ParametersNumba | None = None) -> tuple[ast.FunctionDef, LedgerOfImports]: ...
