from fractions import Fraction

leafExcluderData: dict[str, dict[str, list[tuple[Fraction, int]]]] = {'首一': {'首一': [(Fraction(1, 4), -1),
            (Fraction(1, 2), -2),
            (Fraction(1, 2), -1),
            (Fraction(1, 2), 0),
            (Fraction(1, 2), 1),
            (Fraction(1, 2), 2),
            (Fraction(3, 4), 1)],
      '首一1': [(Fraction(1, 4), -3),
             (Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 2), -3),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2),
             (Fraction(3, 4), 3)],
      '首一三': [(Fraction(1, 4), -3),
             (Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 2),
             (Fraction(1, 4), 3),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2),
             (Fraction(3, 4), 3)],
      '首一三1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2),
              (Fraction(3, 4), 3)],
      '首一二': [(Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(3, 4), -2),
             (Fraction(3, 4), -1),
             (Fraction(3, 4), 0),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首一二1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 1),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2),
              (Fraction(3, 4), 3)],
      '首一二三': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
      '首一二三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
      '首三': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
      '首三1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
      '首二': [(Fraction(1, 4), -1),
            (Fraction(1, 4), 0),
            (Fraction(1, 2), -2),
            (Fraction(1, 2), -1),
            (Fraction(1, 2), 0),
            (Fraction(1, 2), 1),
            (Fraction(1, 2), 2),
            (Fraction(3, 4), 1),
            (Fraction(3, 4), 2)],
      '首二1': [(Fraction(1, 4), -2),
             (Fraction(1, 2), -3),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首二三': [(Fraction(1, 4), 0),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(3, 4), -2),
             (Fraction(3, 4), -1),
             (Fraction(3, 4), 0),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首二三1': [(Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
      '首零': [],
      '首零1': [(Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2)],
      '首零一': [(Fraction(1, 4), -1),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(3, 4), 1)],
      '首零一1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2),
              (Fraction(3, 4), 3)],
      '首零一三': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 4), 1),
              (Fraction(1, 4), 2),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2),
              (Fraction(3, 4), 3)],
      '首零一三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 2),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
      '首零一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
      '首零一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 2),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
      '首零一二三': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
      '首零一二三1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 2), -3),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 0),
                (Fraction(1, 2), 3),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 2)],
      '首零三': [(Fraction(1, 4), -3),
             (Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 2), -3),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 3)],
      '首零三1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1)],
      '首零二': [(Fraction(1, 4), -3),
             (Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 2), -3),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首零二1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 2)],
      '首零二三': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 4), 1),
              (Fraction(1, 4), 2),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 3)],
      '首零二三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 2),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1)]},
'首一三': {'首一': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 2)],
       '首一1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 2)],
       '首一三': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 2), 1), (Fraction(3, 4), 1), (Fraction(3, 4), 3)],
       '首一三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 2)],
       '首一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 2),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
       '首一二三': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
       '首一二三1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 2), -3),
                (Fraction(1, 2), 1),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 2)],
       '首三': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首三1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首二': [(Fraction(1, 4), 0),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
       '首二1': [(Fraction(1, 4), -2),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首二三': [(Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首二三1': [(Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
       '首零': [],
       '首零1': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
       '首零一': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 2)],
       '首零一1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 3)],
       '首零一三': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 3),
               (Fraction(3, 4), 3)],
       '首零一三1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 4), 1),
                (Fraction(1, 4), 2),
                (Fraction(1, 4), 3),
                (Fraction(3, 4), 2),
                (Fraction(3, 4), 3)],
       '首零一二': [(Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
       '首零一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 4), 2),
                (Fraction(1, 2), 1),
                (Fraction(1, 2), 3),
                (Fraction(3, 4), 2)],
       '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -1), (Fraction(1, 2), 1), (Fraction(3, 4), 2)],
       '首零一二三1': [(Fraction(1, 4), -3),
                 (Fraction(1, 4), -2),
                 (Fraction(1, 4), -1),
                 (Fraction(1, 2), -3),
                 (Fraction(1, 2), -2),
                 (Fraction(3, 4), 1),
                 (Fraction(3, 4), 2)],
       '首零三': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 3)],
       '首零三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 3)],
       '首零二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 2),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首零二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2)],
       '首零二三': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 2),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 3)],
       '首零二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 2), 3)]},
'首一二': {'首一': [(Fraction(1, 4), -1), (Fraction(1, 2), 1)],
       '首一1': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), 1)],
       '首一三': [(Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(3, 4), 3)],
       '首一三1': [(Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 2)],
       '首一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
       '首一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), -3), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首一二三1': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首三': [(Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首三1': [(Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首二': [(Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
       '首二1': [(Fraction(1, 4), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首二三': [(Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首二三1': [(Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
       '首零': [],
       '首零1': [(Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
       '首零一': [(Fraction(1, 4), -1), (Fraction(1, 2), 1)],
       '首零一1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1)],
       '首零一三': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 2),
               (Fraction(3, 4), 3)],
       '首零一三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 2)],
       '首零一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 2)],
       '首零一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 1),
                (Fraction(1, 4), 3),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 3)],
       '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 2), -3), (Fraction(3, 4), 2)],
       '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -3), (Fraction(1, 2), -2)],
       '首零三': [(Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 3)],
       '首零三1': [(Fraction(1, 4), 0), (Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 1)],
       '首零二': [(Fraction(1, 4), -1),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 2)],
       '首零二1': [(Fraction(1, 4), -3), (Fraction(1, 4), -1), (Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 0)],
       '首零二三': [(Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3)],
       '首零二三1': [(Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 2)]},
'首一二三': {'首一': [(Fraction(1, 4), -1)],
        '首一1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
        '首一三': [(Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(3, 4), 3)],
        '首一三1': [(Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3)],
        '首一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
        '首一二1': [(Fraction(1, 4), -2),
                (Fraction(1, 4), 0),
                (Fraction(1, 4), 2),
                (Fraction(1, 2), 1),
                (Fraction(1, 2), 3),
                (Fraction(3, 4), 2),
                (Fraction(3, 4), 3)],
        '首一二三': [(Fraction(1, 2), -2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首一二三1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首三': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首三1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首二': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二三': [(Fraction(1, 2), 0), (Fraction(3, 4), -2), (Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二三1': [(Fraction(1, 2), 0), (Fraction(3, 4), -2), (Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零': [],
        '首零1': [(Fraction(1, 2), -1), (Fraction(1, 2), 0)],
        '首零一': [(Fraction(1, 4), -1)],
        '首零一1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -3),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 1)],
        '首零一三': [(Fraction(1, 4), -1), (Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(3, 4), 3)],
        '首零一三1': [(Fraction(1, 4), -3),
                 (Fraction(1, 4), -2),
                 (Fraction(1, 4), -1),
                 (Fraction(1, 4), 0),
                 (Fraction(1, 4), 1),
                 (Fraction(1, 4), 2),
                 (Fraction(1, 4), 3)],
        '首零一二': [(Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), 0),
                (Fraction(3, 4), -2),
                (Fraction(3, 4), -1),
                (Fraction(3, 4), 1)],
        '首零一二1': [(Fraction(1, 4), -3),
                 (Fraction(1, 4), -2),
                 (Fraction(1, 4), -1),
                 (Fraction(1, 4), 0),
                 (Fraction(1, 4), 2),
                 (Fraction(1, 2), 1),
                 (Fraction(1, 2), 3),
                 (Fraction(3, 4), 2)],
        '首零一二三': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2)],
        '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
        '首零三': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
        '首零三1': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
        '首零二': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首零二1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 3)],
        '首零二三': [(Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3)],
        '首零二三1': [(Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3)]},
'首零': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -1)],
      '首一1': [(Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 2), -3),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 2)],
      '首一三': [(Fraction(1, 4), -3),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 4), 1),
             (Fraction(1, 4), 2),
             (Fraction(1, 4), 3),
             (Fraction(3, 4), 3)],
      '首一三1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3), (Fraction(1, 2), 1)],
      '首一二': [(Fraction(1, 4), -2),
             (Fraction(1, 4), -1),
             (Fraction(1, 4), 0),
             (Fraction(1, 2), -2),
             (Fraction(1, 2), 0),
             (Fraction(3, 4), -2),
             (Fraction(3, 4), -1),
             (Fraction(3, 4), 0),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首一二1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 1),
              (Fraction(1, 4), 2),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 2),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 3)],
      '首一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首一二三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), 2)],
      '首三': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
      '首三1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
      '首二': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首二1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首二三': [(Fraction(1, 2), 0), (Fraction(3, 4), -2), (Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首二三1': [(Fraction(1, 2), 0), (Fraction(3, 4), -2), (Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首零': [],
      '首零1': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
      '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -1)],
      '首零一1': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0)],
      '首零一三': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 4), 2), (Fraction(1, 4), 3)],
      '首零一三1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 2),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 1)],
      '首零一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
      '首零一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 3)],
      '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 4), -1), (Fraction(1, 2), -1), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -3), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
      '首零三': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 3)],
      '首零三1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
      '首零二': [(Fraction(1, 2), -2),
             (Fraction(1, 2), -1),
             (Fraction(1, 2), 0),
             (Fraction(1, 2), 1),
             (Fraction(1, 2), 2),
             (Fraction(1, 2), 3),
             (Fraction(3, 4), 1),
             (Fraction(3, 4), 2)],
      '首零二1': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
      '首零二三': [(Fraction(1, 4), 2), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
      '首零二三1': [(Fraction(1, 4), 2), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2)]},
'首零一': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
       '首一1': [(Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1)],
       '首一三': [(Fraction(1, 4), -3),
              (Fraction(1, 4), 2),
              (Fraction(1, 4), 3),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1)],
       '首一三1': [(Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 3)],
       '首一二三': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 2)],
       '首一二三1': [(Fraction(1, 4), -2), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
       '首三': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首三1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首二': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二1': [(Fraction(1, 2), -3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三1': [(Fraction(1, 2), -2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零': [],
       '首零1': [(Fraction(1, 2), -1), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0)],
       '首零一1': [(Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1)],
       '首零一三': [(Fraction(1, 4), 1), (Fraction(1, 4), 2), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
       '首零一三1': [(Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
       '首零一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 1),
                (Fraction(1, 4), 3),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 3)],
       '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
       '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零三': [(Fraction(1, 2), -3),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首零三1': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零二': [(Fraction(1, 4), -3),
              (Fraction(1, 4), -2),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), 2),
              (Fraction(1, 2), 3),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首零二1': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
       '首零二三': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
       '首零二三1': [(Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)]},
'首零一三': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
        '首一1': [(Fraction(1, 4), 0), (Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首一三': [(Fraction(1, 4), -3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首一三1': [(Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 2)],
        '首一二1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 4), 2), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
        '首一二三': [(Fraction(1, 4), -3), (Fraction(3, 4), 1)],
        '首一二三1': [(Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首三': [],
        '首三1': [],
        '首二': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(1, 2), -2), (Fraction(1, 2), 0)],
        '首二1': [(Fraction(1, 2), 1)],
        '首二三': [(Fraction(1, 4), -2), (Fraction(1, 4), -1)],
        '首二三1': [],
        '首零': [],
        '首零1': [(Fraction(1, 2), 2)],
        '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
        '首零一1': [(Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零一三': [(Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零一三1': [(Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零一二': [(Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 0),
                (Fraction(3, 4), -2),
                (Fraction(3, 4), -1),
                (Fraction(3, 4), 1)],
        '首零一二1': [(Fraction(1, 4), -2),
                 (Fraction(1, 4), 0),
                 (Fraction(1, 4), 2),
                 (Fraction(1, 2), 1),
                 (Fraction(1, 2), 3),
                 (Fraction(3, 4), 2),
                 (Fraction(3, 4), 3)],
        '首零一二三': [(Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零一二三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零三': [(Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零二': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1)],
        '首零二1': [(Fraction(1, 2), -1), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零二三': [(Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零二三1': [(Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)]},
'首零一二': {'首一': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2)],
        '首一1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2),
               (Fraction(3, 4), 3)],
        '首一三': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首一三1': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1)],
        '首一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 4), 1),
                (Fraction(1, 4), 3),
                (Fraction(1, 2), 1),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 2),
                (Fraction(3, 4), 3)],
        '首一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首一二三1': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首三': [],
        '首三1': [],
        '首二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2),
              (Fraction(3, 4), 1)],
        '首二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 1)],
        '首二三': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0)],
        '首二三1': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 4), 0)],
        '首零': [],
        '首零1': [(Fraction(1, 2), -1), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首零一': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2)],
        '首零一1': [(Fraction(1, 4), -2),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 0),
                (Fraction(1, 2), 2),
                (Fraction(1, 2), 3),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 2),
                (Fraction(3, 4), 3)],
        '首零一三': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零一三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零一二': [(Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 0),
                (Fraction(3, 4), -2),
                (Fraction(3, 4), -1),
                (Fraction(3, 4), 0),
                (Fraction(3, 4), 2)],
        '首零一二1': [(Fraction(1, 4), -3),
                 (Fraction(1, 4), -1),
                 (Fraction(1, 4), 0),
                 (Fraction(1, 4), 1),
                 (Fraction(1, 4), 3),
                 (Fraction(1, 2), 2),
                 (Fraction(3, 4), 1),
                 (Fraction(3, 4), 2),
                 (Fraction(3, 4), 3)],
        '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零三': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零二': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 2), -3),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
        '首零二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -3),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), 0),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 2),
                (Fraction(3, 4), 3)],
        '首零二三': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)],
        '首零二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)]},
'首零三': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1)],
       '首一1': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -3),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1)],
       '首一三': [(Fraction(1, 4), 0), (Fraction(1, 4), 2), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(3, 4), 3)],
       '首一三1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 4), 1), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(3, 4), -2),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 4), 2),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 3),
               (Fraction(3, 4), 2)],
       '首一二三': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首一二三1': [(Fraction(1, 4), -3), (Fraction(1, 4), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(3, 4), 1)],
       '首三': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首三1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首二': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二1': [(Fraction(1, 4), -2), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三': [(Fraction(3, 4), -2), (Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三1': [(Fraction(3, 4), -1), (Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零': [],
       '首零1': [(Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
       '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1)],
       '首零一1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
       '首零一三': [(Fraction(1, 4), -1), (Fraction(1, 4), 3), (Fraction(1, 2), 1)],
       '首零一三1': [(Fraction(1, 4), 1), (Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首零一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 1)],
       '首零一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -2),
                (Fraction(1, 4), 0),
                (Fraction(1, 4), 2),
                (Fraction(1, 2), 1),
                (Fraction(1, 2), 3),
                (Fraction(3, 4), 2)],
       '首零一二三': [(Fraction(1, 2), 0), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
       '首零一二三1': [(Fraction(1, 4), -3), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
       '首零三': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首零三1': [(Fraction(1, 4), 0), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 2)],
       '首零二': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
       '首零二1': [(Fraction(1, 4), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1)],
       '首零二三': [(Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 3)],
       '首零二三1': [(Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)]},
'首零二': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
       '首一1': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(1, 2), 1),
              (Fraction(1, 2), 2)],
       '首一三': [(Fraction(1, 4), 3), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 3)],
       '首一三1': [(Fraction(1, 4), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首一二': [(Fraction(1, 4), -2),
              (Fraction(1, 4), -1),
              (Fraction(1, 4), 0),
              (Fraction(1, 2), -2),
              (Fraction(1, 2), -1),
              (Fraction(1, 2), 0),
              (Fraction(3, 4), -1),
              (Fraction(3, 4), 0),
              (Fraction(3, 4), 1),
              (Fraction(3, 4), 2)],
       '首一二1': [(Fraction(1, 4), -3),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 1),
               (Fraction(1, 4), 3),
               (Fraction(1, 2), 1),
               (Fraction(1, 2), 2),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 3)],
       '首一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), 1), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首一二三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 2)],
       '首三': [(Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2)],
       '首二': [(Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二1': [(Fraction(1, 4), -2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三': [(Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首二三1': [(Fraction(3, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零': [],
       '首零1': [(Fraction(1, 2), 0), (Fraction(1, 2), 1)],
       '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
       '首零一1': [(Fraction(1, 4), -2), (Fraction(1, 2), -2), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首零一三': [(Fraction(1, 4), -1), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首零一三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首零一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), -1),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 2)],
       '首零一二1': [(Fraction(1, 4), -3),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 1),
                (Fraction(1, 4), 3),
                (Fraction(1, 2), 2),
                (Fraction(3, 4), 1),
                (Fraction(3, 4), 3)],
       '首零一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 1), (Fraction(3, 4), 2)],
       '首零一二三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零三': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首零三1': [(Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
       '首零二': [(Fraction(1, 2), 0), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
       '首零二1': [(Fraction(1, 4), -3), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零二三': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
       '首零二三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 2), (Fraction(3, 4), 3)]},
'首零二三': {'首一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
        '首一1': [(Fraction(1, 2), -2), (Fraction(1, 2), -1), (Fraction(1, 2), 0), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首一三': [(Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首一三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
        '首一二': [(Fraction(1, 4), -2),
               (Fraction(1, 4), -1),
               (Fraction(1, 4), 0),
               (Fraction(1, 2), -2),
               (Fraction(1, 2), -1),
               (Fraction(1, 2), 0),
               (Fraction(3, 4), -2),
               (Fraction(3, 4), 0),
               (Fraction(3, 4), 1),
               (Fraction(3, 4), 2)],
        '首一二1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 4), 2), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
        '首一二三': [(Fraction(1, 4), -3), (Fraction(1, 2), 2), (Fraction(3, 4), 2)],
        '首一二三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首三': [(Fraction(1, 2), 0), (Fraction(1, 2), 2)],
        '首三1': [(Fraction(1, 2), 0), (Fraction(1, 2), 2)],
        '首二': [(Fraction(1, 4), -1), (Fraction(1, 4), 0), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二1': [(Fraction(1, 2), -3), (Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二三': [(Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首二三1': [(Fraction(3, 4), 1), (Fraction(3, 4), 2)],
        '首零': [],
        '首零1': [(Fraction(1, 2), -2), (Fraction(1, 2), 1)],
        '首零一': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), -2), (Fraction(1, 2), -1)],
        '首零一1': [(Fraction(1, 2), -3), (Fraction(1, 2), -2), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首零一三': [(Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首零一三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
        '首零一二': [(Fraction(1, 4), -2),
                (Fraction(1, 4), -1),
                (Fraction(1, 4), 0),
                (Fraction(1, 2), -2),
                (Fraction(1, 2), -1),
                (Fraction(1, 2), 0),
                (Fraction(3, 4), -1),
                (Fraction(3, 4), 1)],
        '首零一二1': [(Fraction(1, 4), -2), (Fraction(1, 4), 0), (Fraction(1, 4), 2), (Fraction(1, 2), 1), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
        '首零一二三': [(Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首零一二三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 2)],
        '首零三': [(Fraction(1, 2), -1), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首零三1': [(Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1)],
        '首零二': [(Fraction(1, 4), -2), (Fraction(1, 4), -1), (Fraction(1, 2), 1), (Fraction(1, 2), 2), (Fraction(3, 4), 1)],
        '首零二1': [(Fraction(1, 2), -3), (Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首零二三': [(Fraction(1, 2), 2), (Fraction(1, 2), 3)],
        '首零二三1': [(Fraction(1, 2), 2), (Fraction(1, 2), 3), (Fraction(3, 4), 1), (Fraction(3, 4), 2), (Fraction(3, 4), 3)]}}
