#=Sin= Import `doTheNeedful` from the selected algorithm: a flow control technique.
# ruff: file-ignore[import-outside-top-level]
"""You can use this module to access the central dispatch functions for all map-folding computations.

This module provides the primary entry points for computing distinct foldings of multidimensional maps
and related OEIS [1] sequences. The module serves as a routing layer that selects and invokes
specialized algorithm implementations based on problem characteristics and user preferences.

The module name 'basecamp' reflects the concept that this module serves as the starting point from
which you can reach any algorithm implementation, analogous to a basecamp from which mountaineers
access any summit route.

Contents
--------
Functions
	countFolds
		You can count distinct foldings of a multidimensional map.
	countFoldsSymmetric
		You can count foldings constrained by rotational symmetry.

Design Goals
------------
Algorithm Version Selection
	This module provides access to any algorithm version. The `countFolds` function is the stable
	interface for multidimensional map folding, including synthetic modules generated by the code
	generation toolchain. The `countFoldsSymmetric` function is the stable interface for symmetric
	folding algorithms. OEIS-specific routing is provided by `mapFolding.oeis.oeisIDfor_n`. Future
	development will add `eliminateFolds` as a stable interface for the experimental
	elimination-based algorithms.

Minimal Preprocessing
	This module quickly routes to the algorithm or algorithm dispatcher (typically named
	`doTheNeedful`). Preparatory work happens in the downstream algorithm modules, not in this
	basecamp module.

OEIS Identifier Usability
	OEIS identifiers are meaningless labels without context. The module's data structures (via
	`dictionaryOEIS` [3]) provide sequence descriptions alongside identifiers so users can work with
	domain concepts rather than memorizing arbitrary codes. That said, current evidence suggests the
	package has only one user (the author).

References
----------
[1] OEIS - The On-Line Encyclopedia of Integer Sequences
	https://oeis.org/
[2] Meanders - Wikipedia
	https://en.wikipedia.org/wiki/Meander_(mathematics)
[3] mapFolding.oeis
	Internal package reference (metadata for OEIS sequences)

"""
from __future__ import annotations

from mapFolding.algorithms.matrixMeandersShare import initializeDictionaryMeanders
from mapFolding.beDRY import defineProcessorLimit, getLeavesTotal, getTaskDivisions, mapShapeIs2上nDimensions, validateMapShape
from mapFolding.dataBaskets import MapFoldingState, MatrixMeandersState, ParallelMapFoldingState, SymmetricFoldsState
from mapFolding.kitFilesystem import makePathFilenameCount, makePathFilenameFolds, saveTotal, saveTotalFAILearly
from mapFolding.theSSOT import settingsPackage
from typing import TYPE_CHECKING

if TYPE_CHECKING:
	from collections.abc import Sequence
	from hunterMakesPy.theTypes import Limitation
	from os import PathLike
	from pathlib import Path
	from typing import Literal, LiteralString

def countFolds(mapShape: Sequence[int]
				, flow: Literal['daoOfMapFolding', 'numba', 'theorem2', 'theorem2Codon', 'theorem2Numba', 'theorem2Trimmed'] | LiteralString | None = None
				, pathLikeWrite: PathLike[str] | None = None
				, *
				, CPUlimit: Limitation = None
				, computationDivisions: int | str | None = None
				, suffix: str = ".foldsTotal"
				) -> int:
	"""
	Count the number of distinct ways to fold a map.

	Mathematicians also describe this as folding a strip of stamps, and they usually call the total
	"number of distinct ways to fold" a map the map's "foldings."

	Parameters
	----------
	mapShape : Sequence[int]
		A sequence containing the positive integer length of each dimension of the map to be folded.
	pathLikeWrite : PathLike[str] | None = None
		A filename, a path of only directories, or a path with directories and a filename to which
		`countFolds` will write the total. If `pathLikeWrite` is a path of only directories,
		`countFolds` creates a filename based on the map dimensions.
	computationDivisions : int | str | None = None
		Whether and how to divide the computational work.
		- `None`: no division of the computation into tasks.
		- `int`: into how many tasks `countFolds` will divide the computation. The values 0 or 1 are
		identical to `None`. It is mathematically impossible to divide the computation into more tasks
		than the map's total leaves.
		- 'maximum': divides the computation into `leavesTotal`-many tasks.
		- 'cpu': divides the computation into the number of available CPUs.
	CPUlimit : bool | float | int | None = None
		If relevant, whether and how to limit the number of processors `countFolds` will use.
		- `False`, `None`, or `0`: No limits on processor usage; uses all available processors. All
		other values will potentially limit processor usage.
		- `True`: Yes, limit the processor usage; limits to 1 processor.
		- `int >= 1`: The maximum number of available processors to use.
		- `0 < float < 1`: The maximum number of processors to use expressed as a fraction of
		available processors.
		- `-1 < float < 0`: The number of processors to *not* use expressed as a fraction of available
		processors.
		- `int <= -1`: The number of available processors to *not* use.
		- If the value of `CPUlimit` is a `float` greater than 1 or less than -1, `countFolds`
		truncates the value to an `int` with the same sign as the `float`.
	flow : Literal['daoOfMapFolding', 'numba', 'theorem2', 'theorem2Codon', 'theorem2Numba', 'theorem2Trimmed'] | LiteralString | None = None
		My stupid way of selecting the version of the algorithm to use in the computation. There are
		certainly better ways to do this, but I have not yet solved this issue.

	Returns
	-------
	foldsTotal : int
		Number of distinct ways to fold a map of the given dimensions.

	Using `computationDivisions`
	----------------------------
	You probably do not want to divide your computation into tasks.

	Dividing the algorithm into tasks is inherently inefficient: between 50% and 90% of the work done
	by every task must be done by each task. In some cases, you will increase the total computation
	time, but if you improve the computation time, it will only change by -10 to -50% depending on (at
	the very least) the ratio of the map dimensions, the number of leaves, and the ratio of
	`leavesTotal` to logicalCores.

	If an undivided computation would take 10 hours on your computer, for example, the computation
	will take at least 5 hours, you might reduce the time to 9 hours, but most of the time, you will
	increase the computation time. If logicalCores >= `leavesTotal`, the computation will probably be
	faster. If logicalCores <= 2 * `leavesTotal`, it will almost certainly be slower.
	"""
	mapShape = validateMapShape(mapShape)

#-------- task division instructions -----------------------------------------------------

	if computationDivisions:
		concurrencyLimit: int = defineProcessorLimit(CPUlimit, settingsPackage.concurrencyPackage)
		taskDivisions: int = getTaskDivisions(computationDivisions, concurrencyLimit, getLeavesTotal(mapShape))
	else:
		concurrencyLimit = 1
		taskDivisions = 0

#-------- memorialization instructions ---------------------------------------------

	if pathLikeWrite is None:
		pathFilenameFoldsTotal: Path | None = None
	else:
		pathFilenameFoldsTotal = saveTotalFAILearly(makePathFilenameFolds(mapShape, pathLikeWrite, suffix=suffix))

#-------- Algorithm version -----------------------------------------------------

	if 0 in mapShape:
		""" I don't think 0 is a valid number of panels in a dimension. I think some offset values on OEIS are wrong.
		| oeisID  | offset | mapShape                      | Equivalencies to offset 1            |
		| ------- | ------ | ----------------------------- | ------------------------------------ |
		| A000136 | 1      | (1,) or (1, 1)                |                                      |
		| A001415 | 0      | (2, 0)                        | a(1) = A000136(2), a(2) = A001418(2) |
		| A001416 | 0      | (3, 0)                        | a(1) = A000136(3), a(3) = A001418(3) |
		| A001417 | 0      | Let p ∈ {2}. ∴ (p,) * 0 or () | a(1) = A000136(2), a(2) = A001418(2) |
		| A001418 | 1      | (1, 1)                        |                                      |
		| A195646 | 0      | Let p ∈ {3}. ∴ (p,) * 0 or () | a(1) = A000136(3), a(2) = A001418(3) |
		"""
		foldsTotal = 1
	elif 1 < taskDivisions:
		from mapFolding.syntheticModules.countParallelNumba import doTheNeedful

		mapFoldingParallelState: ParallelMapFoldingState = ParallelMapFoldingState(mapShape, taskDivisions=taskDivisions)

		# `listStatesParallel` exists so you can research the parallel computation.
		foldsTotal, _listStatesParallel = doTheNeedful(mapFoldingParallelState, concurrencyLimit)

	else:
		if flow == 'daoOfMapFolding':
			from mapFolding.algorithms.daoOfMapFolding import doTheNeedful
		elif any(map((2).__lt__, mapShape)) or mapShapeIs2上nDimensions(mapShape, youMustBeDimensionsTallToRideThis=2):
			match flow:
				case 'theorem2':
					from mapFolding.syntheticModules.theorem2 import doTheNeedful
				case 'theorem2Codon':
					from mapFolding.syntheticModules.codon.theorem2 import doTheNeedful
				case 'theorem2Numba':
					from mapFolding.syntheticModules.theorem2Numba import doTheNeedful
				case 'theorem2Trimmed':
					from mapFolding.syntheticModules.theorem2Trimmed import doTheNeedful
				case _:
					from mapFolding.syntheticModules.theorem2 import doTheNeedful
		else:
			match flow:
				case 'numba':
					from mapFolding.syntheticModules.daoOfMapFoldingNumba import doTheNeedful
				case _:
					from mapFolding.algorithms.daoOfMapFolding import doTheNeedful

		mapFoldingState: MapFoldingState = MapFoldingState(mapShape)
		mapFoldingState = doTheNeedful(mapFoldingState)
		foldsTotal = mapFoldingState.foldsTotal

#-------- Follow memorialization instructions ---------------------------------------------

	if pathFilenameFoldsTotal is not None:
		saveTotal(pathFilenameFoldsTotal, foldsTotal)

	return foldsTotal

def countFoldsSymmetric(mapShape: tuple[int, ...], flow: LiteralString | Literal['algorithm', 'asynchronous', 'theorem2', 'theorem2Codon', 'theorem2Numba', 'theorem2Trimmed', ''] = '', pathLikeWrite: PathLike[str] | None = None, *, CPUlimit: Limitation = None, suffix: str = ".foldsTotal") -> int:
	"""Count foldings constrained by rotational symmetry.

	(AI generated docstring)

	You can use this function to count the symmetric foldings described by OEIS A007822 [1]. For
	sequence index `n`, set `mapShape` to `(1, 2 * n)`, not `(1, 2 * n + 1)`. Although A007822
	describes foldings of `2 * n + 1` stamps, this calculation expects `mapShape` to be `(1, 2 * n)`.

	Parameters
	----------
	mapShape : tuple[int, ...]
		The strip dimensions, expressed as `(1, 2 * n)` for sequence index `n`.
	flow : str | Literal['algorithm', 'asynchronous', 'theorem2', 'theorem2Codon', 'theorem2Numba', 'theorem2Trimmed', ''] = ''
		The counting method. `'algorithm'` or `''` selects the standard method. The other supported values select
		alternative methods with the same result.
	pathLikeWrite : PathLike[str] | None = None
		An optional file or directory path for saving the count. A directory path receives a filename
		based on `mapShape`.
	CPUlimit : Limitation = None
		The processor limit for the `'asynchronous'` method. `None`, `False`, and `0` allow all
		available processors; `True` limits the calculation to one processor. An `int` sets or reserves
		a number of processors, and a `float` sets or reserves a fraction of available processors.
	suffix : str = ".foldsTotal"
		The filename suffix for the saved count.

	Returns
	-------
	symmetricFolds : int
		The number of distinct foldings that satisfy the rotational-symmetry constraint.

	References
	----------
	[1] A007822 - Number of symmetric foldings of 2n+1 stamps - OEIS
		https://oeis.org/A007822
	"""
	mapShape = validateMapShape(mapShape)

#-------- memorialization instructions ---------------------------------------------

	if pathLikeWrite is None:
		pathFilenameFoldsTotal: Path | None = None
	else:
		pathFilenameFoldsTotal = saveTotalFAILearly(makePathFilenameFolds(mapShape, pathLikeWrite, suffix=suffix))

#-------- Algorithm version -----------------------------------------------------

	if flow == 'asynchronous':
		from mapFolding.syntheticModules.foldsSymmetric.asynchronous import doTheNeedful
		foldsTotal = doTheNeedful(SymmetricFoldsState(mapShape), defineProcessorLimit(CPUlimit)).symmetricFolds
	else:
		match flow:
			case 'theorem2':
				from mapFolding.syntheticModules.foldsSymmetric.theorem2 import doTheNeedful
			case 'theorem2Codon':
				from mapFolding.syntheticModules.foldsSymmetric.codon.theorem2 import doTheNeedful
			case 'theorem2Numba':
				from mapFolding.syntheticModules.foldsSymmetric.theorem2Numba import doTheNeedful
			case 'theorem2Trimmed':
				from mapFolding.syntheticModules.foldsSymmetric.theorem2Trimmed import doTheNeedful
			case 'algorithm' | _:
				from mapFolding.syntheticModules.foldsSymmetric.algorithm import doTheNeedful

		symmetricState: SymmetricFoldsState = SymmetricFoldsState(mapShape)

		symmetricState = doTheNeedful(symmetricState)
		foldsTotal = symmetricState.symmetricFolds

#-------- Follow memorialization instructions ---------------------------------------------

	if pathFilenameFoldsTotal is not None:
		saveTotal(pathFilenameFoldsTotal, foldsTotal)

	return foldsTotal

#=Sin= `CPUlimit` is in the signature due to `KeywordArgumentsCount`.
# ruff: ignore[unused-function-argument]
def countMeanders(
	kind: Literal['semi', 'meanders'] | LiteralString
	, n: int
	, flow: Literal['matrixMeanders', 'matrixNumPy', 'matrixPandas'] | LiteralString | None = None
	, pathLikeWrite: PathLike[str] | None = None
	, *
	, CPUlimit: Limitation = None
	, suffix: str = ".countTotal"
) -> int:
	"""Compute a native meander sequence term.

	Parameters
	----------
	kind : Literal['semi', 'meanders']
		Whether to compute semi-meanders or meanders.
	n : int
		Sequence index.
	flow : Literal['matrixMeanders', 'matrixNumPy', 'matrixPandas'] | LiteralString | None = None
		Algorithm selection.
	pathLikeWrite : PathLike[str] | None = None
		Optional output path for the computed total.
	CPUlimit : bool | float | int | None = None
		Unused.

	Returns
	-------
	countTotal : int
		The number of semi-meanders or meanders for the given index.
	"""
#-------- memorialization instructions ---------------------------------------------

	if pathLikeWrite is None:
		pathFilenameCountTotal: Path | None = None
	else:
		pathFilenameCountTotal = saveTotalFAILearly(makePathFilenameCount(pathLikeWrite, kind, str(n), suffix=suffix))

#-------- Algorithm selection and execution ---------------------------------------------

	if kind == 'semi' and n == 1:
		countTotal: int = 1
	else:
		match flow:
			case 'matrixNumPy':
				from mapFolding.algorithms.matrixMeandersNumPy import doTheNeedful
			case 'matrixPandas':
				from mapFolding.algorithms.matrixMeandersPandas import doTheNeedful
			case 'matrixMeanders' | _:
				from mapFolding.algorithms.matrixMeanders import doTheNeedful

		boundary: int = n - 1
		dictionaryMeanders: dict[int, int] = initializeDictionaryMeanders(kind, n, boundary)
		state: MatrixMeandersState = MatrixMeandersState(n, kind, boundary, dictionaryMeanders)
		countTotal: int = doTheNeedful(state)

#-------- Follow memorialization instructions ---------------------------------------------

	if pathFilenameCountTotal is not None:
		saveTotal(pathFilenameCountTotal, countTotal)

	return countTotal
