# ruff: file-ignore[import-outside-top-level]
# ruff: file-ignore[redundant-literal-union]
# ruff: file-ignore[unused-function-argument]
# ty:ignore[invalid-argument-type]
# TODO the following diagnostic suggest to me that there is a better paradigm for the flow control.
# pyright: reportArgumentType=false
"""You can use this module to access the central dispatch functions for all map-folding computations.

This module provides the primary entry points for computing distinct foldings of multidimensional maps
and related OEIS [1] sequences. The module serves as a routing layer that selects and invokes
specialized algorithm implementations based on problem characteristics and user preferences.

The module name 'basecamp' reflects the concept that this module serves as the starting point from
which you can reach any algorithm implementation, analogous to a basecamp from which mountaineers
access any summit route.

Contents
--------
Functions
	countFolds
		You can count distinct foldings of a multidimensional map.
	countFoldsSymmetric
		You can count foldings constrained by rotational symmetry.

Design Goals
------------
Algorithm Version Selection
	This module provides access to any algorithm version. The `countFolds` function is the stable
	interface for multidimensional map folding, including synthetic modules generated by the code
	generation toolchain. The `countFoldsSymmetric` function is the stable interface for symmetric
	folding algorithms. OEIS-specific routing is provided by `mapFolding.oeis.oeisIDfor_n`. Future
	development will add `eliminateFolds` as a stable interface for the experimental
	elimination-based algorithms.

Minimal Preprocessing
	This module quickly routes to the algorithm or algorithm dispatcher (typically named
	`doTheNeedful`). Preparatory work happens in the downstream algorithm modules, not in this
	basecamp module.

OEIS Identifier Usability
	OEIS identifiers are meaningless labels without context. The module's data structures (via
	`dictionaryOEIS` [3]) provide sequence descriptions alongside identifiers so users can work with
	domain concepts rather than memorizing arbitrary codes. That said, current evidence suggests the
	package has only one user (the author).

References
----------
[1] OEIS - The On-Line Encyclopedia of Integer Sequences
	https://oeis.org/
[2] Meanders - Wikipedia
	https://en.wikipedia.org/wiki/Meander_(mathematics)
[3] mapFolding.oeis
	Internal package reference (metadata for OEIS sequences)

"""
from __future__ import annotations

from mapFolding._e._2上nDimensional import mapShapeIs2上nDimensions
from mapFolding.beDRY import defineProcessorLimit, getLeavesTotal, getTaskDivisions, validateListDimensions
from mapFolding.kitFilesystem import getPathFilenameFoldsTotal, getPathRootJobDEFAULT, saveFoldsTotal, saveFoldsTotalFAILearly
from mapFolding.theSSOT import settingsPackage
from pathlib import Path
from typing import Literal, TYPE_CHECKING

if TYPE_CHECKING:
	from collections.abc import Sequence
	from hunterMakesPy.theTypes import Limitation
	from os import PathLike

def countFolds(listDimensions: Sequence[int] | None = None
				, pathLikeWriteTotal: PathLike[str] | None = None
				, computationDivisions: int | str | None = None
				, *
				, CPUlimit: Limitation = None
				, mapShape: tuple[int, ...] | None = None
				, flow: str = ''
				) -> int:
	"""
	Count the number of distinct ways to fold a map.

	Mathematicians also describe this as folding a strip of stamps, and they usually call the total "number of distinct ways to
	fold" a map the map's "foldings."

	Parameters
	----------
	listDimensions : Sequence[int] | None = None
		List of integers representing the dimensions of the map to be folded.
	pathLikeWriteTotal : PathLike[str] | None = None
		A filename, a path of only directories, or a path with directories and a filename to which `countFolds` will write the
		value of `foldsTotal`. If `pathLikeWriteTotal` is a path of only directories, `countFolds` creates a filename based
		on the map dimensions.
	computationDivisions : int | str | None = None
		Whether and how to divide the computational work.
		- `None`: no division of the computation into tasks.
		- `int`: into how many tasks `countFolds` will divide the computation. The values 0 or 1 are identical to `None`. It is
		mathematically impossible to divide the computation into more tasks than the map's total leaves.
		- 'maximum': divides the computation into `leavesTotal`-many tasks.
		- 'cpu': divides the computation into the number of available CPUs.
	CPUlimit : bool | float | int | None = None
		If relevant, whether and how to limit the number of processors `countFolds` will use.
		- `False`, `None`, or `0`: No limits on processor usage; uses all available processors. All other values will
		potentially limit processor usage.
		- `True`: Yes, limit the processor usage; limits to 1 processor.
		- `int >= 1`: The maximum number of available processors to use.
		- `0 < float < 1`: The maximum number of processors to use expressed as a fraction of available processors.
		- `-1 < float < 0`: The number of processors to *not* use expressed as a fraction of available processors.
		- `int <= -1`: The number of available processors to *not* use.
		- If the value of `CPUlimit` is a `float` greater than 1 or less than -1, `countFolds` truncates the value to an `int`
		with the same sign as the `float`.
	mapShape : tuple[int, ...] | None = None
		Tuple of integers representing the dimensions of the map to be folded. Mathematicians almost always use the term
		"dimensions", such as in the seminal paper, "Multi-dimensional map-folding". Nevertheless, in contemporary Python
		programming, in the context of these algorithms, the term "shape" makes it much easier to align the mathematics with the
		syntax of the programming language.
	flow : str = ''
		My stupid way of selecting the version of the algorithm to use in the computation. There are certainly better ways to do
		this, but I have not yet solved this issue. As of 2025 Aug 14, these values will work:
		- '' selects the default algorithm
		- 'daoOfMapFolding'
		- 'numba'
		- 'theorem2'
		- 'theorem2Codon'
		- 'theorem2Numba'
		- 'theorem2Trimmed'

	Returns
	-------
	foldsTotal : int
		Number of distinct ways to fold a map of the given dimensions.

	Note well
	---------
	You probably do not want to divide your computation into tasks.

	If you want to compute a large `foldsTotal`, dividing the computation into tasks is usually a bad idea. Dividing the
	algorithm into tasks is inherently inefficient: efficient division into tasks means there would be no overlap in the
	work performed by each task. When dividing this algorithm, the amount of overlap is between 50% and 90% by all
	tasks: at least 50% of the work done by every task must be done by each task. If you improve the computation time,
	it will only change by -10 to -50% depending on (at the very least) the ratio of the map dimensions and the number
	of leaves. If an undivided computation would take 10 hours on your computer, for example, the computation will still
	take at least 5 hours but you might reduce the time to 9 hours. Most of the time, however, you will increase the
	computation time. If logicalCores >= `leavesTotal`, it will probably be faster. If logicalCores <= 2 * `leavesTotal`, it
	will almost certainly be slower for all map dimensions.
	"""
#-------- mapShape ---------------------------------------------------------------------

	if mapShape:
		mapShape = validateListDimensions(mapShape)
	elif listDimensions:
		mapShape = validateListDimensions(listDimensions)

	if mapShape is None:
		message: str = (f"I received `{listDimensions = }` and `{mapShape = }`, but I was unable to select a map for which to count the folds.")
		raise ValueError(message)

#-------- task division instructions -----------------------------------------------------

	if computationDivisions:
		concurrencyLimit: int = defineProcessorLimit(CPUlimit, settingsPackage.concurrencyPackage)
		taskDivisions: int = getTaskDivisions(computationDivisions, concurrencyLimit, getLeavesTotal(mapShape))
	else:
		concurrencyLimit = 1
		taskDivisions = 0

#-------- memorialization instructions ---------------------------------------------

	if pathLikeWriteTotal is not None:
		pathFilenameFoldsTotal: Path | None = getPathFilenameFoldsTotal(mapShape, pathLikeWriteTotal)
		saveFoldsTotalFAILearly(pathFilenameFoldsTotal)
	else:
		pathFilenameFoldsTotal = None

#-------- Algorithm version -----------------------------------------------------

	if 1 < taskDivisions:
		from mapFolding.dataBaskets import ParallelMapFoldingState
		from mapFolding.syntheticModules.countParallelNumba import doTheNeedful

		mapFoldingParallelState: ParallelMapFoldingState = ParallelMapFoldingState(mapShape, taskDivisions=taskDivisions)

		# `listStatesParallel` exists so you can research the parallel computation.
		foldsTotal, _listStatesParallel = doTheNeedful(mapFoldingParallelState, concurrencyLimit)

	elif flow == 'asynchronousSymmetric':
		from mapFolding.dataBaskets import SymmetricFoldsState
		from mapFolding.syntheticModules.foldsSymmetric.asynchronous import doTheNeedful
		foldsTotal = doTheNeedful(SymmetricFoldsState(mapShape), defineProcessorLimit(CPUlimit)).symmetricFolds
	elif flow.endswith('Symmetric'):
		if flow == 'theorem2Symmetric':
			from mapFolding.syntheticModules.foldsSymmetric.theorem2 import doTheNeedful
		elif flow == 'theorem2CodonSymmetric':
			from mapFolding.syntheticModules.foldsSymmetric.codon.theorem2 import doTheNeedful
		elif flow == 'theorem2NumbaSymmetric':
			from mapFolding.syntheticModules.foldsSymmetric.theorem2Numba import doTheNeedful
		elif flow == 'theorem2TrimmedSymmetric':
			from mapFolding.syntheticModules.foldsSymmetric.theorem2Trimmed import doTheNeedful
		else:
			from mapFolding.syntheticModules.foldsSymmetric.algorithm import doTheNeedful

		from mapFolding.dataBaskets import SymmetricFoldsState
		symmetricState: SymmetricFoldsState = SymmetricFoldsState(mapShape)

		symmetricState = doTheNeedful(symmetricState)
		foldsTotal = symmetricState.symmetricFolds

	else:
		if flow in {'daoOfMapFolding', ''}:
			from mapFolding.algorithms.daoOfMapFolding import doTheNeedful
		elif flow == 'numba':
			from mapFolding.syntheticModules.daoOfMapFoldingNumba import doTheNeedful
		elif any(map((2).__lt__, mapShape)) or mapShapeIs2上nDimensions(mapShape):
			if flow == 'theorem2':
				from mapFolding.syntheticModules.theorem2 import doTheNeedful
			elif flow == 'theorem2Codon':
				from mapFolding.syntheticModules.codon.theorem2 import doTheNeedful
			elif flow == 'theorem2Numba':
				from mapFolding.syntheticModules.theorem2Numba import doTheNeedful
			elif flow == 'theorem2Trimmed':
				from mapFolding.syntheticModules.theorem2Trimmed import doTheNeedful
			else:
				from mapFolding.syntheticModules.theorem2 import doTheNeedful
		else:
			from mapFolding.algorithms.daoOfMapFolding import doTheNeedful

		from mapFolding.dataBaskets import MapFoldingState
		mapFoldingState: MapFoldingState = MapFoldingState(mapShape)
		mapFoldingState = doTheNeedful(mapFoldingState)
		foldsTotal = mapFoldingState.foldsTotal

#-------- Follow memorialization instructions ---------------------------------------------

	if pathFilenameFoldsTotal is not None:
		saveFoldsTotal(pathFilenameFoldsTotal, foldsTotal)

	return foldsTotal

# DOCUMENT, possibly in multiple locations, that the map shape is (1, 2n) not (1, 2n+1). Or rather,
# the algorithm uses (1, 2n).
def countFoldsSymmetric(mapShape: tuple[int, ...], flow: str | Literal['asynchronous', 'theorem2', 'theorem2Codon', 'theorem2Numba', 'theorem2Trimmed', ''] = '', pathLikeWriteTotal: PathLike[str] | None = None, *, CPUlimit: Limitation = None) -> int:
	return countFolds(None, pathLikeWriteTotal, None, CPUlimit=CPUlimit, mapShape=mapShape, flow=f'{flow}Symmetric')

def countMeanders(oeisID: str, oeis_n: int, flow: str = '', pathLikeWriteTotal: PathLike[str] | None = None, *, CPUlimit: Limitation = None) -> int:
	"""Compute a native meander sequence term.

	This entry point computes A000682 and A005316 with a matrix meander algorithm. Formula and
	symmetric-folding dispatch belongs to `oeisIDfor_n`.

	Parameters
	----------
	oeisID : str
		'A000682' or 'A005316'.
	oeis_n : int
		Sequence index.
	flow : str = ''
		'matrixMeanders' or '' for the native implementation, 'matrixNumPy', or 'matrixPandas'.
	pathLikeWriteTotal : PathLike[str] | None = None
		Optional output path for the computed total.
	CPUlimit : bool | float | int | None = None
		Processor limit from the shared counting entry-point contract.

	Returns
	-------
	countTotal : int
		The requested sequence term.

	Raises
	------
	ValueError
		If `oeisID` is not A000682 or A005316.

	Examples
	--------
	>>> from mapFolding.oeis import countMeanders
	>>> countMeanders('A000682', 5, flow='matrixMeanders')
	42

	See Also
	--------
	mapFolding.oeis.oeisIDfor_n
		Dispatch every implemented OEIS sequence.

	"""
#-------- memorialization instructions ---------------------------------------------

	if pathLikeWriteTotal is not None:
		filenameCountTotal: str = f"{oeisID}_n{oeis_n}.countTotal"
		pathLikeSherpa = Path(pathLikeWriteTotal)
		if pathLikeSherpa.is_dir():
			pathFilenameFoldsTotal = pathLikeSherpa / filenameCountTotal
		elif pathLikeSherpa.is_file() and pathLikeSherpa.is_absolute():
			pathFilenameFoldsTotal = pathLikeSherpa
		else:
			pathFilenameFoldsTotal = getPathRootJobDEFAULT() / pathLikeSherpa
		pathFilenameFoldsTotal.parent.mkdir(parents=True, exist_ok=True)
		saveFoldsTotalFAILearly(pathFilenameFoldsTotal)
	else:
		pathFilenameFoldsTotal = None

#-------- Algorithm selection and execution ---------------------------------------------

	match flow:
		case 'matrixNumPy':
			from mapFolding.algorithms.matrixMeandersNumPy import doTheNeedful
			from mapFolding.dataBaskets import MatrixMeandersNumPyState as State
		case 'matrixPandas':
			from mapFolding.algorithms.matrixMeandersPandas import doTheNeedful
			from mapFolding.dataBaskets import MatrixMeandersNumPyState as State
		case 'matrixMeanders' | _:
			from mapFolding.algorithms.matrixMeanders import doTheNeedful
			from mapFolding.dataBaskets import MatrixMeandersState as State

	boundary: int = oeis_n - 1

	# TODO Consider: If A000682 is essentially A000136 * leavesTotal, then my graphs of A000136 are
	# _literal_ graphs of A000682. Since Theorem 2 applies to A000136, it must apply to A000682. Can I
	# use the graphs to find the midpoint of an A000682 computation using the matrix algorithm? The
	# problem with the matrix algorithm is memory usage. Unique signatures (buckets) grows
	# predictably. Cutting the count in half... In `doTheNeedful`, I used `while state.boundary > 0:`
	# and the ratio trick to find the midpoint: it didn't work.
	if oeisID == 'A000682':
		if oeis_n == 1:
			return 1
		elif oeis_n & 0b1:
			arcCode: int = 0b101
		else:
			arcCode = 0b1
		listArcCodes: list[int] = [(arcCode << 1) | arcCode]
#													   0b1010 | 0b0101 is 0b1111, or 0xf
#														 0b10 |   0b01 is   0b11, or 0x3

		MAXIMUMarcCode: int = 1 << (2 * boundary + 4)
		while listArcCodes[-1] < MAXIMUMarcCode:
			arcCode = (arcCode << 4) | 0b0101  # e.g., 0b 10000 | 0b 0101 = 0b 10101
			listArcCodes.append((arcCode << 1) | arcCode)  # e.g., 0b 101010 | 0b 1010101 = 0b 111111 = 0x3f
			# Thereafter, append 0b1111 or 0xf, so, e.g., 0x3f, 0x3ff, 0x3fff, 0x3ffff, ...
			# See "mapFolding/reference/A000682facts.py"
		dictionaryMeanders: dict[int, int] = dict.fromkeys(listArcCodes, 1)

	elif oeisID == 'A005316':
		if oeis_n & 0b1:
			dictionaryMeanders: dict[int, int] = {0b1111: 1}  # 0xf
		else:
			dictionaryMeanders = {0b10110: 1}
	else:
		message: str = f"I received `{oeisID = }` for meander computation, but I only support 'A000682' and 'A005316'."
		raise ValueError(message)

	state = State(oeis_n, oeisID, boundary, dictionaryMeanders)
	countTotal: int = doTheNeedful(state)

#-------- Follow memorialization instructions ---------------------------------------------

	if pathFilenameFoldsTotal is not None:
		saveFoldsTotal(pathFilenameFoldsTotal, countTotal)

	return countTotal
