
name: Codecov Coverage
on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed]

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: coverage-data
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./tests/coverage/coverage.xml
          fail_ci_if_error: true
