name: Update CITATION.cff

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  processCitation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Process citation update
        run: |
          python -m pip install updateCitation
          python -c "import updateCitation; updateCitation.here()"

      - name: Commit and push if changed
        run: |
          git config user.name "updateCitation"
          git config user.email "2958419+hunterhogan@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update citations [skip ci]"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
